plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.fizzer.lib'
    compileSdk 37

    defaultConfig {
        applicationId "com.fizzer.lib"
        minSdk 23
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        viewBinding = true
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.google.material
    implementation libs.androidx.constraintlayout
    implementation project(path: ':FizzerBaseLib')
    implementation project(path: ':FizzerWidget')
}
